FSPACERFINAL/Controllers/DriveCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FSPACERFINAL.Data;
using FSPACERFINAL.Models;

namespace FSPACERFINAL.Controllers
{
    public class DriveCardsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DriveCardsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DriveCards
        public async Task<IActionResult> Index()
        {
            return View(await _context.DriveCards.ToListAsync());
        }

        // GET: DriveCards/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driveCard = await _context.DriveCards
                .SingleOrDefaultAsync(m => m.DriveNumber == id);
            if (driveCard == null)
            {
                return NotFound();
            }

            return View(driveCard);
        }

        // GET: DriveCards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DriveCards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Model,Ratio,DriveNumber,GearNumber")] DriveCard driveCard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(driveCard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(driveCard);
        }

        // GET: DriveCards/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driveCard = await _context.DriveCards.SingleOrDefaultAsync(m => m.DriveNumber == id);
            if (driveCard == null)
            {
                return NotFound();
            }
            return View(driveCard);
        }

        // POST: DriveCards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Model,Ratio,DriveNumber,GearNumber")] DriveCard driveCard)
        {
            if (id != driveCard.DriveNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(driveCard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DriveCardExists(driveCard.DriveNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(driveCard);
        }

        // GET: DriveCards/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driveCard = await _context.DriveCards
                .SingleOrDefaultAsync(m => m.DriveNumber == id);
            if (driveCard == null)
            {
                return NotFound();
            }

            return View(driveCard);
        }

        // POST: DriveCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var driveCard = await _context.DriveCards.SingleOrDefaultAsync(m => m.DriveNumber == id);
            _context.DriveCards.Remove(driveCard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DriveCardExists(string id)
        {
            return _context.DriveCards.Any(e => e.DriveNumber == id);
        }
    }
}

FSPACERFINAL/Controllers/OperatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FSPACERFINAL.Data;
using FSPACERFINAL.Models;

namespace FSPACERFINAL.Controllers
{
    public class OperatorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OperatorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Operators
        public async Task<IActionResult> Index()
        {
            return View(await _context.Operators.ToListAsync());
        }

        // GET: Operators/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @operator = await _context.Operators
                .SingleOrDefaultAsync(m => m.ID == id);
            if (@operator == null)
            {
                return NotFound();
            }

            return View(@operator);
        }

        // GET: Operators/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Operators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName")] Operator @operator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@operator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@operator);
        }

        // GET: Operators/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @operator = await _context.Operators.SingleOrDefaultAsync(m => m.ID == id);
            if (@operator == null)
            {
                return NotFound();
            }
            return View(@operator);
        }

        // POST: Operators/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName")] Operator @operator)
        {
            if (id != @operator.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@operator);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OperatorExists(@operator.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@operator);
        }

        // GET: Operators/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @operator = await _context.Operators
                .SingleOrDefaultAsync(m => m.ID == id);
            if (@operator == null)
            {
                return NotFound();
            }

            return View(@operator);
        }

        // POST: Operators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @operator = await _context.Operators.SingleOrDefaultAsync(m => m.ID == id);
            _context.Operators.Remove(@operator);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OperatorExists(int id)
        {
            return _context.Operators.Any(e => e.ID == id);
        }
    }
}

FSPACERFINAL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - FSPACERFINAL</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="masthead">
        <div class="wrap push">

            <a href="#menu" class="menu-link">&#9776;</a>

            <h1>FSpacer Length Calculator</h1>
            <p class="subtitle">Gear Company</p>

        </div> <!-- /.wrap -->
    </div> <!-- /.masthead-->

    <nav id="menu" class="panel" role="navigation">
       <a href="@Url.Action("FirstPage", "SpacerCards")">
            <img src="@Url.Content("~/images/Gear.png")" width="100"/>
        </a>
        <ul>         
            <li><a asp-area="" asp-controller="SpacerCards" asp-action="Front">FSpacer Card</a></li>            
            <li><a asp-area="" asp-controller="SpacerCards" asp-action="SearchActive"> Search Active Cards</a></li>           
            <li><a asp-area="" asp-controller="SpacerCards" asp-action="SearchCards">Search</a></li>
            <li><a asp-area="" asp-controller="SpacerCards" asp-action="Index">Card Database</a></li>
            <li><a asp-area="" asp-controller="Operators" asp-action="Index">Operator Database</a></li>
            <li><a asp-area="" asp-controller="DriveCards" asp-action="Index">Drive Card Database</a></li>
        </ul>
    </nav>

    
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FSPACERFINAL</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="SpacerCards" asp-action="SearchCards">Search</a></li>
                    <li><a asp-area="" asp-controller="SpacerCards" asp-action="SearchActive">Search Active Card</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - FSPACERFINAL</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>